name = "hosting-cloudflare-worker"
account_id = "d5e85419ead2ddaf4385090f7be422a1"
compatibility_date = "2025-07-31"
workers_dev = false

routes = [
  { pattern = "hadialhassan.dev/*", zone_name = "hadialhassan.dev" },
  { pattern = "www.hadialhassan.dev/*", zone_name = "hadialhassan.dev" }
]

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"

