name = "hosting-cloudflare-worker"
account_id = "${CF_ACCOUNT_ID}"
compatibility_date = "2025-07-31"
workers_dev = false

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"

routes = [
  { pattern = "hadialhassan.dev/*", zone_name = "hadialhassan.dev" },
  { pattern = "www.hadialhassan.dev/*", zone_name = "hadialhassan.dev" }
]